export const MOCK_CATEGORIES = [
  { id: "cat-phones", name: "Phones", slug: "phones" },
  { id: "cat-parts", name: "Parts", slug: "parts" },
  { id: "cat-tools", name: "Tools", slug: "tools" },
  { id: "cat-accessories", name: "Accessories", slug: "accessories" },
];

export const MOCK_PRODUCTS = [
  // Phones (Apple)
  {
    id: "ph-apple-16pm-256",
    category_id: "cat-phones",
    name: "Apple iPhone 16 Pro Max (256GB)",
    slug: "apple-iphone-16-pro-max-256",
    description: 'A18 Pro, 6.9" Super Retina XDR, Titanium design. Flagship performance and cameras.',
    price_inr: 159900,
    discount_percent: 5,
    brand: "Apple",
    image_url: "/images/product-phone.svg",
    specs: [
      "6.9\" 120Hz OLED",
      "A18 Pro chipset",
      "Triple camera with 5x telephoto",
    ],
    best_seller: true,
    warranty_months: 12,
  },
  {
    id: "ph-google-pixel8pro-256",
    category_id: "cat-phones",
    name: "Google Pixel 8 Pro (256GB)",
    slug: "google-pixel-8-pro-256",
    description: "Tensor G3, best Pixel camera, 7 years of updates.",
    price_inr: 99999,
    discount_percent: 12,
    brand: "Google",
    image_url: "/images/product-phone.svg",
    specs: ["6.7\" LTPO OLED", "Tensor G3", "Triple camera"],
  },
  {
    id: "ph-vivo-v30pro-256",
    category_id: "cat-phones",
    name: "Vivo V30 Pro (256GB)",
    slug: "vivo-v30-pro-256",
    description: "Zeiss camera tuning, slim design, vibrant display.",
    price_inr: 38999,
    discount_percent: 10,
    brand: "Vivo",
    image_url: "/images/product-phone.svg",
    specs: ["6.78\" 120Hz AMOLED", "Dimensity 8200", "Zeiss portrait"],
  },
  {
    id: "ph-oppo-reno12pro-256",
    category_id: "cat-phones",
    name: "OPPO Reno 12 Pro (256GB)",
    slug: "oppo-reno-12-pro-256",
    description: "Sleek design, strong selfie camera, fast charging.",
    price_inr: 42999,
    discount_percent: 9,
    brand: "OPPO",
    image_url: "/images/product-phone.svg",
    specs: ["6.7\" 120Hz AMOLED", "Dimensity 9200", "50MP triple"],
  },
  {
    id: "ph-realme-12proplus-256",
    category_id: "cat-phones",
    name: "realme 12 Pro+ (256GB)",
    slug: "realme-12-pro-plus-256",
    description: "Periscope camera at a great price, curved display.",
    price_inr: 32999,
    discount_percent: 8,
    brand: "realme",
    image_url: "/images/product-phone.svg",
    specs: ["6.7\" 120Hz OLED", "Snapdragon 7s Gen 2", "64MP periscope"],
  },
  {
    id: "ph-moto-edge50pro-256",
    category_id: "cat-phones",
    name: "Motorola Edge 50 Pro (256GB)",
    slug: "motorola-edge-50-pro-256",
    description: "Clean Android, fast charging, stylish vegan leather.",
    price_inr: 34999,
    discount_percent: 7,
    brand: "Motorola",
    image_url: "/images/product-phone.svg",
    specs: ["6.7\" pOLED 144Hz", "Snapdragon 7 Gen 3", "50MP OIS"],
  },
  {
    id: "ph-nothing-2a-256",
    category_id: "cat-phones",
    name: "Nothing Phone (2a) (256GB)",
    slug: "nothing-phone-2a-256",
    description: "Glyph interface, clean software, standout design.",
    price_inr: 27999,
    discount_percent: 6,
    brand: "Nothing",
    image_url: "/images/product-phone.svg",
    specs: ["6.7\" 120Hz OLED", "Dimensity 7200 Pro", "Glyph lights"],
  },
  {
    id: "ph-iqoo-neo9pro-256",
    category_id: "cat-phones",
    name: "iQOO Neo 9 Pro (256GB)",
    slug: "iqoo-neo-9-pro-256",
    description: "Gaming performance, VC cooling, great value.",
    price_inr: 34999,
    discount_percent: 10,
    brand: "iQOO",
    image_url: "/images/product-phone.svg",
    specs: ["6.78\" 120Hz AMOLED", "Snapdragon 8 Gen 2", "Vapor cooling"],
  },
  {
    id: "ph-infinix-note40pro-256",
    category_id: "cat-phones",
    name: "Infinix Note 40 Pro (256GB)",
    slug: "infinix-note-40-pro-256",
    description: "Big battery, curved display, solid budget pick.",
    price_inr: 21999,
    discount_percent: 5,
    brand: "Infinix",
    image_url: "/images/product-phone.svg",
    specs: ["6.78\" 120Hz AMOLED", "Helio G99", "5000mAh"],
  },
  {
    id: "ph-tecno-camon30-256",
    category_id: "cat-phones",
    name: "Tecno Camon 30 (256GB)",
    slug: "tecno-camon-30-256",
    description: "Great selfies, flashy design, value oriented.",
    price_inr: 19999,
    discount_percent: 6,
    brand: "Tecno",
    image_url: "/images/product-phone.svg",
    specs: ["6.78\" 120Hz", "Dimensity 7020", "50MP"],
  },
  {
    id: "ph-asus-rog8-256",
    category_id: "cat-phones",
    name: "ASUS ROG Phone 8 (256GB)",
    slug: "asus-rog-phone-8-256",
    description: "Top-tier gaming performance, triggers, long battery.",
    price_inr: 89999,
    discount_percent: 10,
    brand: "ASUS",
    image_url: "/images/product-phone.svg",
    specs: ["6.78\" 165Hz AMOLED", "Snapdragon 8 Gen 3", "Gaming triggers"],
  },
  {
    id: "ph-poco-f6pro-256",
    category_id: "cat-phones",
    name: "POCO F6 Pro (256GB)",
    slug: "poco-f6-pro-256",
    description: "Flagship specs for less, fast charging.",
    price_inr: 39999,
    discount_percent: 9,
    brand: "POCO",
    image_url: "/images/product-phone.svg",
    specs: ["6.67\" 120Hz AMOLED", "Snapdragon 8 Gen 2", "120W charge"],
  },
  {
    id: "ph-nokia-x30-128",
    category_id: "cat-phones",
    name: "Nokia X30 (128GB)",
    slug: "nokia-x30-128",
    description: "Eco-friendly build, clean Android, sturdy design.",
    price_inr: 29999,
    discount_percent: 7,
    brand: "Nokia",
    image_url: "/images/product-phone.svg",
    specs: ["6.43\" 90Hz AMOLED", "Snapdragon 695", "50MP OIS"],
  },
  {
    id: "ph-honor-90-256",
    category_id: "cat-phones",
    name: "HONOR 90 (256GB)",
    slug: "honor-90-256",
    description: "Curved display, 200MP camera, sleek.",
    price_inr: 31999,
    discount_percent: 8,
    brand: "HONOR",
    image_url: "/images/product-phone.svg",
    specs: ["6.7\" 120Hz AMOLED", "Snapdragon 7 Gen 1", "200MP"],
  },
  {
    id: "ph-apple-16p-256",
    category_id: "cat-phones",
    name: "Apple iPhone 16 Pro (256GB)",
    slug: "apple-iphone-16-pro-256",
    description: "A18 Pro performance in a compact titanium body. ProMotion and Pro cameras.",
    price_inr: 139900,
    discount_percent: 6,
    brand: "Apple",
    image_url: "/images/product-phone.svg",
    specs: [
      "6.3\" 120Hz OLED",
      "A18 Pro chipset",
      "Triple camera system",
    ],
  },
  {
    id: "ph-apple-16-128",
    category_id: "cat-phones",
    name: "Apple iPhone 16 (128GB)",
    slug: "apple-iphone-16-128",
    description: "A18 chip, long battery life, excellent cameras. Great all-round iPhone.",
    price_inr: 79900,
    discount_percent: 4,
    brand: "Apple",
    image_url: "/images/product-tool.svg",
    specs: [
      "6.1\" OLED display",
      "A18 chip",
      "Dual‑camera system",
    ],
  },
  {
    id: "ph-apple-15pm-256",
    category_id: "cat-phones",
    name: "Apple iPhone 15 Pro Max (256GB)",
    slug: "apple-iphone-15-pro-max-256",
    description: "A17 Pro, titanium, 5x tetraprism telephoto, USB‑C, action button.",
    price_inr: 149900,
    discount_percent: 10,
    brand: "Apple",
    image_url: "/images/product-tool.svg",
    specs: [
      "6.7\" 120Hz OLED",
      "A17 Pro",
      "48MP main + 5x telephoto",
    ],
  },
  {
    id: "ph-apple-15p-256",
    category_id: "cat-phones",
    name: "Apple iPhone 15 Pro (256GB)",
    slug: "apple-iphone-15-pro-256",
    description: "A17 Pro, titanium, ProMotion display, triple camera system.",
    price_inr: 124900,
    discount_percent: 9,
    brand: "Apple",
    image_url: "/placeholder.svg",
    specs: [
      "6.1\" 120Hz OLED",
      "A17 Pro",
      "Triple camera",
    ],
  },
  {
    id: "ph-apple-15-128",
    category_id: "cat-phones",
    name: "Apple iPhone 15 (128GB)",
    slug: "apple-iphone-15-128",
    description: "A16 Bionic, Dynamic Island, USB‑C, excellent everyday phone.",
    price_inr: 69900,
    discount_percent: 7,
    brand: "Apple",
    image_url: "/placeholder.svg",
    specs: [
      "6.1\" OLED",
      "A16 Bionic",
      "48MP main camera",
    ],
  },
  {
    id: "ph-apple-14-128",
    category_id: "cat-phones",
    name: "Apple iPhone 14 (128GB)",
    slug: "apple-iphone-14-128",
    description: "A15 Bionic, dual-camera system, crash detection, solid value.",
    price_inr: 56900,
    discount_percent: 8,
    brand: "Apple",
    image_url: "/placeholder.svg",
    specs: [
      "6.1\" OLED",
      "A15 Bionic",
      "Dual camera",
    ],
  },
  {
    id: "ph-apple-13-128",
    category_id: "cat-phones",
    name: "Apple iPhone 13 (128GB)",
    slug: "apple-iphone-13-128",
    description: "A15 Bionic performance, bright OLED, dependable battery life.",
    price_inr: 52900,
    discount_percent: 12,
    brand: "Apple",
    image_url: "/placeholder.svg",
    specs: [
      "6.1\" OLED",
      "A15 Bionic",
      "12MP dual camera",
    ],
  },

  // Phones (Samsung)
  {
    id: "ph-sam-s24u-256",
    category_id: "cat-phones",
    name: "Samsung Galaxy S24 Ultra (256GB)",
    slug: "samsung-galaxy-s24-ultra-256",
    description: "Snapdragon 8 Gen 3, 200MP camera, S Pen, massive battery, LTPO display.",
    price_inr: 129999,
    discount_percent: 11,
    brand: "Samsung",
    image_url: "/placeholder.svg",
    specs: [
      "6.8\" LTPO 120Hz",
      "Snapdragon 8 Gen 3",
      "200MP quad camera + S Pen",
    ],
    best_seller: true,
    warranty_months: 12,
  },
  {
    id: "ph-sam-s24-256",
    category_id: "cat-phones",
    name: "Samsung Galaxy S24 (256GB)",
    slug: "samsung-galaxy-s24-256",
    description: "Compact flagship with bright AMOLED, long software support, strong cameras.",
    price_inr: 79999,
    discount_percent: 9,
    brand: "Samsung",
    image_url: "/placeholder.svg",
    specs: [
      "6.2\" 120Hz AMOLED",
      "Exynos/Snapdragon 8 Gen",
      "Triple camera",
    ],
  },
  {
    id: "ph-sam-a55-128",
    category_id: "cat-phones",
    name: "Samsung Galaxy A55 (128GB)",
    slug: "samsung-galaxy-a55-128",
    description: "Balanced mid-ranger with great display and battery life.",
    price_inr: 35999,
    discount_percent: 6,
    brand: "Samsung",
    image_url: "/placeholder.svg",
    specs: [
      "6.6\" 120Hz AMOLED",
      "Exynos 1480",
      "50MP triple camera",
    ],
  },

  // Phones (Xiaomi)
  {
    id: "ph-xiaomi-14-256",
    category_id: "cat-phones",
    name: "Xiaomi 14 (256GB)",
    slug: "xiaomi-14-256",
    description: "Leica cameras, Snapdragon 8 Gen 3, compact flagship experience.",
    price_inr: 69999,
    discount_percent: 10,
    brand: "Xiaomi",
    image_url: "/placeholder.svg",
    specs: [
      "6.36\" 120Hz AMOLED",
      "Snapdragon 8 Gen 3",
      "50MP Leica triple camera",
    ],
  },
  {
    id: "ph-xiaomi-note13pro-256",
    category_id: "cat-phones",
    name: "Redmi Note 13 Pro (256GB)",
    slug: "redmi-note-13-pro-256",
    description: "120Hz AMOLED, solid cameras, value-packed mid-range phone.",
    price_inr: 26999,
    discount_percent: 8,
    brand: "Xiaomi",
    image_url: "/placeholder.svg",
    specs: [
      "6.67\" 120Hz AMOLED",
      "Snapdragon 7s Gen 2",
      "200MP camera",
    ],
  },

  // Phones (OnePlus)
  {
    id: "ph-oneplus-12-256",
    category_id: "cat-phones",
    name: "OnePlus 12 (256GB)",
    slug: "oneplus-12-256",
    description: "Snapdragon 8 Gen 3, Hasselblad cameras, fast charging, smooth OxygenOS.",
    price_inr: 64999,
    discount_percent: 7,
    brand: "OnePlus",
    image_url: "/placeholder.svg",
    specs: [
      "6.82\" 120Hz AMOLED",
      "Snapdragon 8 Gen 3",
      "Hasselblad triple camera",
    ],
  },
  {
    id: "ph-oneplus-nord4-256",
    category_id: "cat-phones",
    name: "OnePlus Nord 4 (256GB)",
    slug: "oneplus-nord-4-256",
    description: "Reliable performance, premium build, excellent for the price.",
    price_inr: 32999,
    discount_percent: 6,
    brand: "OnePlus",
    image_url: "/placeholder.svg",
    specs: [
      "6.74\" 120Hz AMOLED",
      "Snapdragon 7+ Gen 3",
      "50MP dual camera",
    ],
  },

  // Phones (Google)
  {
    id: "ph-google-pixel8-128",
    category_id: "cat-phones",
    name: "Google Pixel 8 (128GB)",
    slug: "google-pixel-8-128",
    description: "Tensor G3, best-in-class computational photography, clean Android.",
    price_inr: 75999,
    discount_percent: 13,
    brand: "Google",
    image_url: "/placeholder.svg",
    specs: [
      "6.2\" 120Hz OLED",
      "Tensor G3",
      "Best-in-class camera",
    ],
  },
  {
    id: "ph-google-pixel8a-128",
    category_id: "cat-phones",
    name: "Google Pixel 8a (128GB)",
    slug: "google-pixel-8a-128",
    description: "Affordable Pixel experience with excellent camera and software support.",
    price_inr: 45999,
    discount_percent: 9,
    brand: "Google",
    image_url: "/placeholder.svg",
    specs: [
      "6.1\" 120Hz OLED",
      "Tensor G3",
      "Pixel-class camera",
    ],
  },

  // Accessories
  {
    id: "acc-apple-usbc-20w",
    category_id: "cat-accessories",
    name: "Apple 20W USB‑C Power Adapter",
    slug: "apple-20w-usbc-power-adapter",
    description: "Genuine fast charger for iPhone and iPad. BIS certified.",
    price_inr: 1890,
    discount_percent: 5,
    brand: "Apple",
    image_url: "/images/product-accessory.svg",
    specs: [
      "20W USB‑C",
      "BIS certified",
      "1-year warranty",
    ],
  },
  {
    id: "acc-magsafe-charger",
    category_id: "cat-accessories",
    name: "MagSafe Charger",
    slug: "apple-magsafe-charger",
    description: "Magnetic wireless charging for iPhone 12 and later.",
    price_inr: 4500,
    discount_percent: 4,
    brand: "Apple",
    image_url: "/images/product-accessory.svg",
    specs: [
      "MagSafe",
      "Up to 15W",
      "Qi2 compatible",
    ],
  },
  {
    id: "acc-usbc-cable-1m",
    category_id: "cat-accessories",
    name: "USB‑C to USB‑C Cable (1m)",
    slug: "usb-c-to-usb-c-cable-1m",
    description: "Durable braided cable for fast charging and data.",
    price_inr: 699,
    discount_percent: 10,
    brand: "Anker",
    image_url: "/images/product-accessory.svg",
    specs: ["1 meter", "60W PD", "Braided"],
  },
  {
    id: "acc-lightning-cable-1m",
    category_id: "cat-accessories",
    name: "USB‑C to Lightning Cable (1m)",
    slug: "usb-c-to-lightning-cable-1m",
    description: "MFi-certified fast charging cable for iPhone.",
    price_inr: 1499,
    discount_percent: 8,
    brand: "Belkin",
    image_url: "/images/product-accessory.svg",
    specs: ["1 meter", "MFi", "Fast charge"],
  },
  {
    id: "acc-tempered-glass-iphone15",
    category_id: "cat-accessories",
    name: "Tempered Glass — iPhone 15",
    slug: "tempered-glass-iphone-15",
    description: "9H hardness with oleophobic coating.",
    price_inr: 599,
    discount_percent: 15,
    brand: "Spigen",
    image_url: "/images/product-accessory.svg",
    specs: ["9H", "Edge-to-edge", "Easy install"],
    warranty_months: 6,
  },
  {
    id: "acc-case-iphone15",
    category_id: "cat-accessories",
    name: "Case — iPhone 15 (MagSafe)",
    slug: "case-iphone-15-magsafe",
    description: "Shock-absorbing TPU with MagSafe ring.",
    price_inr: 1999,
    discount_percent: 12,
    brand: "Caseology",
    image_url: "/images/product-accessory.svg",
    specs: ["MagSafe", "Drop protection", "Raised lips"],
  },

  // Parts & Tools (inspired by iFixit / MobileSentrix / 2UUL)
  {
    id: "part-iphone16pm-battery",
    category_id: "cat-parts",
    name: "Genuine Battery — iPhone 16 Pro Max",
    slug: "genuine-battery-iphone-16-pro-max",
    description: "OEM battery replacement compatible with iPhone 16 Pro Max. Calibrated, 1-year warranty.",
    price_inr: 12999,
    discount_percent: 3,
    brand: "Apple",
    image_url: "/images/product-part.svg",
    specs: [
      "OEM grade",
      "Calibrated",
      "1-year warranty",
    ],
  },
  {
    id: "part-iphone16pm-display",
    category_id: "cat-parts",
    name: "Genuine OLED Display — iPhone 16 Pro Max",
    slug: "genuine-oled-display-iphone-16-pro-max",
    description: "Premium OLED with ceramic shield compatibility, True Tone restore supported.",
    price_inr: 34999,
    discount_percent: 5,
    brand: "Apple",
    image_url: "/images/product-part.svg",
    specs: [
      "Genuine OLED",
      "True Tone compatible",
      "Quality tested",
    ],
    warranty_months: 6,
  },
  {
    id: "part-iphone13-battery",
    category_id: "cat-parts",
    name: "Battery — iPhone 13",
    slug: "battery-iphone-13",
    description: "High-cycle replacement with safety certifications.",
    price_inr: 6999,
    discount_percent: 6,
    brand: "Apple",
    image_url: "/images/product-part.svg",
    specs: ["High-cycle", "CE/ROHS", "1-year warranty"],
  },
  {
    id: "part-samsung-s24-ultra-display",
    category_id: "cat-parts",
    name: "OLED Display — Galaxy S24 Ultra",
    slug: "oled-display-galaxy-s24-ultra",
    description: "AMOLED panel with adhesive and frame.",
    price_inr: 27999,
    discount_percent: 5,
    brand: "Samsung",
    image_url: "/images/product-part.svg",
    specs: ["AMOLED", "With frame", "Adhesive included"],
  },
  {
    id: "tool-2uul-precision-kit",
    category_id: "cat-tools",
    name: "2UUL Precision Driver Kit (38-in-1)",
    slug: "2uul-precision-driver-kit-38",
    description: "High-precision screwdriver set for smartphone repair, anti-slip handle, magnetized bits.",
    price_inr: 2499,
    discount_percent: 10,
    brand: "2UUL",
    image_url: "/placeholder.svg",
    specs: [
      "38 bits",
      "Magnetized",
      "Anti-slip handle",
    ],
  },
  {
    id: "tool-soldering-75w",
    category_id: "cat-tools",
    name: "Soldering Station 75W",
    slug: "soldering-station-75w",
    description: "Temperature controlled soldering station for board repair.",
    price_inr: 8999,
    discount_percent: 0,
    brand: "Generic",
    image_url: "/placeholder.svg",
    specs: [
      "75W adjustable",
      "ESD safe",
      "Rapid heat-up",
    ],
  },
];

export const MOCK_SERVICES = [
  { id: "s1", name: "Screen Replacement", description: "Cracked or unresponsive screen repair.", price_inr: 3499, duration_minutes: 60 },
  { id: "s3", name: "Water Damage", description: "Diagnostics and board-level cleaning.", price_inr: 1999, duration_minutes: 120 },
];

export const MOCK_BUYBACK_MODELS = [
  { device_category: "phone", brand: "Apple", model: "iPhone 15 Pro Max", base_price_inr: 90000 },
  { device_category: "phone", brand: "Apple", model: "iPhone 14 Pro Max", base_price_inr: 80000 },
  { device_category: "phone", brand: "Apple", model: "iPhone 13 Pro Max", base_price_inr: 65000 },
  { device_category: "phone", brand: "Apple", model: "iPhone 12", base_price_inr: 40000 },
  { device_category: "phone", brand: "Apple", model: "iPhone 11", base_price_inr: 30000 },
  { device_category: "phone", brand: "Samsung", model: "Galaxy S24 Ultra", base_price_inr: 95000 },
  { device_category: "phone", brand: "Samsung", model: "Galaxy S23 Ultra", base_price_inr: 80000 },
  { device_category: "phone", brand: "Samsung", model: "Galaxy S22 Ultra", base_price_inr: 60000 },
  { device_category: "phone", brand: "Samsung", model: "Galaxy S21 FE", base_price_inr: 35000 },
  { device_category: "phone", brand: "Samsung", model: "Galaxy Note 20 Ultra", base_price_inr: 50000 },
  { device_category: "phone", brand: "OnePlus", model: "12 Pro", base_price_inr: 60000 },
  { device_category: "phone", brand: "OnePlus", model: "11R", base_price_inr: 35000 },
  { device_category: "phone", brand: "OnePlus", model: "9 Pro", base_price_inr: 30000 },
  { device_category: "phone", brand: "OnePlus", model: "Nord 3", base_price_inr: 22000 },
  { device_category: "phone", brand: "Xiaomi", model: "14 Pro", base_price_inr: 50000 },
  { device_category: "phone", brand: "Xiaomi", model: "Mi 11 Ultra", base_price_inr: 30000 },
  { device_category: "phone", brand: "Xiaomi", model: "Redmi Note 13 Pro+", base_price_inr: 25000 },
  { device_category: "phone", brand: "Realme", model: "GT 5 Pro", base_price_inr: 40000 },
  { device_category: "phone", brand: "Realme", model: "GT Neo 2", base_price_inr: 22000 },
  { device_category: "phone", brand: "Vivo", model: "X100 Pro", base_price_inr: 55000 },
  { device_category: "phone", brand: "Vivo", model: "X70 Pro+", base_price_inr: 27000 },
  { device_category: "phone", brand: "Oppo", model: "Find X7 Ultra", base_price_inr: 60000 },
  { device_category: "phone", brand: "Oppo", model: "Find X3 Pro", base_price_inr: 29000 },
  { device_category: "phone", brand: "Google", model: "Pixel 8 Pro", base_price_inr: 65000 },
  { device_category: "phone", brand: "Google", model: "Pixel 7 Pro", base_price_inr: 50000 },
  { device_category: "phone", brand: "Google", model: "Pixel 6 Pro", base_price_inr: 40000 },
  { device_category: "phone", brand: "Motorola", model: "Edge 40 Pro", base_price_inr: 35000 },
  { device_category: "phone", brand: "Motorola", model: "Razr 40 Ultra", base_price_inr: 50000 },
  { device_category: "phone", brand: "Asus", model: "ROG Phone 7", base_price_inr: 60000 },
  { device_category: "phone", brand: "Asus", model: "Zenfone 10", base_price_inr: 35000 },
  { device_category: "phone", brand: "Nothing", model: "Phone (2)", base_price_inr: 35000 },
  { device_category: "phone", brand: "Nothing", model: "Phone (1)", base_price_inr: 20000 },
  { device_category: "phone", brand: "Poco", model: "F5 Pro", base_price_inr: 25000 },
  { device_category: "phone", brand: "Poco", model: "X6 Pro", base_price_inr: 18000 },
  { device_category: "phone", brand: "Infinix", model: "Zero 30 5G", base_price_inr: 16000 },
  { device_category: "phone", brand: "Tecno", model: "Phantom V Flip", base_price_inr: 30000 },
  { device_category: "phone", brand: "Honor", model: "Magic 6 Pro", base_price_inr: 60000 },
  { device_category: "phone", brand: "Lava", model: "Agni 2", base_price_inr: 12000 },
  { device_category: "phone", brand: "Micromax", model: "IN Note 2", base_price_inr: 10000 },
  { device_category: "phone", brand: "iQOO", model: "Neo 9 Pro", base_price_inr: 30000 },
  { device_category: "phone", brand: "iQOO", model: "11", base_price_inr: 35000 },
  { device_category: "phone", brand: "Sony", model: "Xperia 1 V", base_price_inr: 60000 },
  { device_category: "phone", brand: "Sony", model: "Xperia 10 IV", base_price_inr: 25000 },
  { device_category: "phone", brand: "Nokia", model: "G60 5G", base_price_inr: 18000 },
  { device_category: "phone", brand: "Nokia", model: "X30 5G", base_price_inr: 25000 },
  { device_category: "phone", brand: "Panasonic", model: "Eluga Ray 810", base_price_inr: 9000 },
  { device_category: "phone", brand: "Lenovo", model: "Legion Phone Duel 2", base_price_inr: 40000 },
  { device_category: "phone", brand: "HTC", model: "U23 Pro", base_price_inr: 35000 },
  { device_category: "phone", brand: "BlackBerry", model: "Key2", base_price_inr: 20000 },
  { device_category: "phone", brand: "Alcatel", model: "3X 2020", base_price_inr: 8000 },
  { device_category: "phone", brand: "Gionee", model: "M12 Pro", base_price_inr: 9000 },
  { device_category: "phone", brand: "Coolpad", model: "Cool 20 Pro", base_price_inr: 10000 },
  { device_category: "phone", brand: "Meizu", model: "18 Pro", base_price_inr: 30000 },
  { device_category: "phone", brand: "ZTE", model: "Axon 40 Ultra", base_price_inr: 35000 },
  { device_category: "phone", brand: "Sharp", model: "Aquos R7", base_price_inr: 40000 },
  { device_category: "phone", brand: "Apple", model: "iPhone 11", base_price_inr: 16000 },
  { device_category: "phone", brand: "Samsung", model: "Galaxy S24 Ultra", base_price_inr: 68000 },
  { device_category: "phone", brand: "Samsung", model: "Galaxy S24", base_price_inr: 42000 },
  { device_category: "phone", brand: "Samsung", model: "Galaxy A55", base_price_inr: 18000 },
  { device_category: "phone", brand: "Google", model: "Pixel 8", base_price_inr: 38000 },
  { device_category: "phone", brand: "Google", model: "Pixel 8a", base_price_inr: 24000 },
  { device_category: "phone", brand: "OnePlus", model: "OnePlus 12", base_price_inr: 36000 },
  { device_category: "phone", brand: "OnePlus", model: "OnePlus Nord 4", base_price_inr: 18000 },
  { device_category: "phone", brand: "Xiaomi", model: "Xiaomi 14", base_price_inr: 34000 },
  { device_category: "phone", brand: "Xiaomi", model: "Redmi Note 13 Pro", base_price_inr: 14000 },
];

export const MOCK_COURSES = [
  { id: "c1", title: "Mobile Repair Basics", description: "Beginner essentials for diagnostics and parts replacement.", price_inr: 4999, level: "Beginner" },
  { id: "c2", title: "Board Level Repair", description: "Advanced micro-soldering and circuit repair techniques.", price_inr: 14999, level: "Advanced" },
];

export const MOCK_BLOG_POSTS = [
  { id: "b1", title: "How to Pick Genuine Parts", excerpt: "Tips for sourcing authentic parts and avoiding fakes.", status: "published", cover_image_url: null, published_at: new Date().toISOString() },
  { id: "b2", title: "Battery Health Myths", excerpt: "We debunk common battery myths and best practices.", status: "published", cover_image_url: null, published_at: new Date().toISOString() },
];

export const MOCK_VIDEOS = [
  { id: "v1", title: "iPhone Screen Replace", youtube_id: "dQw4w9WgXcQ", description: "Step-by-step screen replacement." },
  { id: "v2", title: "Microsoldering Basics", youtube_id: "V-_O7nl0Ii0", description: "Intro to board-level repair tools." },
];


